/**
 * @author Created by felix on 17-8-31.
 * @email   307253927@qq.com
 */
'use strict';

module.exports = {
  RECORDER_SAVE      : "RECORDER_SAVE",
  RECORDER           : "RECORDER",
  RECORDER_INIT      : 'RECORDER_INIT',
  RECORDER_RECEIVE   : "RECORDER_RECEIVE",
  RECORDER_END       : "RECORDER_END",
  RECORDER_MAIN_READY: "RECORDER_MAIN_READY",
  RECORDER_MAIN_ERR  : "RECORDER_MAIN_ERR",
  
  TRANS_VOICE: "TRANS_VOICE",
  TRANS_PCM  : "TRANS_PCM",
  
  CONFIG           : "CONFIG",
  MEETING          : "MEETING",
  MEETING_CREATE   : "MEETING_CREATE",
  MEETING_SAVE     : "MEETING_SAVE",
  MEETING_SAVE_TEXT: "MEETING_SAVE_TEXT"
}