/**
 * @author Created by felix on 17-8-31.
 * @email   307253927@qq.com
 */
'use strict';

module.exports = {
  SAVE_RECORDER      : "SAVE_RECORDER",
  RECORDER           : "RECORDER",
  RECORDER_INIT      : 'RECORDER_INIT',
  RECORDER_RECEIVE   : "RECORDER_RECEIVE",
  RECORDER_END       : "RECORDER_END",
  RECORDER_MAIN_READY: "RECORDER_MAIN_READY",
  RECORDER_MAIN_ERR  : "RECORDER_MAIN_ERR",
  
  CONFIG        : "CONFIG",
  MEETING       : "MEETING",
  MEETING_CREATE: "MEETING_CREATE",
  MEETING_SAVE  : "MEETING_SAVE"
}